{% set name = "BespON" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a75cd7e62746fb0fef9b98aa157a44f9ed2ef63e952f7ae4ec5b3c2892669187

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - bespon

about:
  home: http://github.com/gpoore/bespon_py
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for BespON
  description: |
    The bespon package for Python encodes and decodes
    data in the BespON format.
  doc_url: http://github.com/gpoore/bespon_py
  dev_url: http://github.com/gpoore/bespon_py

extra:
  recipe-maintainers:
    - mwcraig
    - gpoore
