{% set name = "BespON" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f2bda67fea8ee95c8aa7e885835ab88bdbfa392a94077ce1c9d29017420ce7a

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - bespon

about:
  home: http://github.com/gpoore/bespon_py
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for BespON
  description: |
    The bespon package for Python encodes and decodes
    data in the BespON format.
  doc_url: http://github.com/gpoore/bespon_py
  dev_url: http://github.com/gpoore/bespon_py

extra:
  recipe-maintainers:
    - mwcraig
    - gpoore
