travis:
  secure:
    BINSTAR_TOKEN: xygLUBQhUR1p02YoEnGXfcmLvGd6FeeWB9ARKyxWO+pufgbzxzm4n3MQ4PqpqcbqMFU+LS6vAiJA7EzMuHtdWzXUEGHUz1hUG77L93xdgNwRHXwh510qEPoaffNQOrC0Jb20c1XrkcFizg4UmAr+6pV0fifbd+M6W8K+3XQelQJuGfnKUMJRuwEaZkW4AtmxhunH6CgS3jhjMoTXKR69J+5F1JJsO7n4SevkKYFfqloio7WE8H5DwYdwKqZf1AymC8DpVS+Y6Y55QiqXrgKQHwWflhx55h4RvX53BZ/PwX25cIokPKezjGqExyTPtK6XldtZjG/GCjvCPOlMnn+5l0eHtHbNZio+xVe3BFi6srfzaDlMY+n8h2yJ4sVi47nshgatQiQM1rHymk9LTzvc24ndjqrnAVHfV8wGzj9rwl5SV+YPUgKLA341sxcCs2Jm1e1rYPzVdc7KqTGCvzJ/cdmAuzhigz1Iug4LmyvOEa5JUMbwVxssJGFRiqtSo7DJjSw20InOpz3Zprka/LgIKuex2Z3RYx6nXC+hv14Qb6xry1t4eGkFkwQ7rUbL4tWaQYAx3phKsCAG/Og67r5hKnH5Q+PPCuOdEiv3AfFKb24eKLD2giDgHseGwyDJq8JUgl2ImnSGcLzGMkDpzRGu5TUpjGja+L/UbJRWdjgLdhU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
