travis:
  secure:
    BINSTAR_TOKEN: gmaSuSsbpCZ0fGtKy0FbfBxIJDJX/iPbnUTefXM1JRur3f+UkyyldOHNnQP45hYCRKzY8TVDzDWKU8dSaZgmZnOOBrCMCxyejD+9o5KE/Jr+nqxVS6BoECNZA+3me3xWaGgkkeNLsISb33QYtCeEWo9xekfRw4x3wtEqLSnxeztMYEVTINyb4lrjnuSzMkSaFiKRcOCmPzE4bOm4mtS4wXgm2llkUuNBIuzrqL3Oj1nBi+MVZMEAUmvhj6pOnUnZSvXW6cL2J00oVZ3Ux49KHM1sOUdi41r2snf14sCDhCBOmnvWRWH7JG5E75Nhfog5ohi48Vez5gHWP2mrhpYrQC+KFbc23Qi4zY5zLyVSrBYin0raFBHTH8BqJhNqAhgrJSDncpj5af9WTgUmgCi4bFWyY2e2O6j3HTmC6MVcNqOQg4pU+Si9Ct7i9meDbbGQl2hyWrQVtT3KNWjQu5Bj+xliQf/vy8/UKIjBw1ipPH3CTSc3qpGgMX8+uAhp8/Kb7gwuUddeV4blUV00Xdagb0IRHAOAU+QI6Rr46kQm/0O4oAVFgvH3lD6s7TsFu+UAVehIkmYaxoN97Vine2fZXbH7ZrumDYm2+q6SQR6m0dGpMZloLkkpkDqjhc7aBfX94JtfRArTJoI9Vr+wS5q8eKK6Wruhy4OkN8aTaEIw/SM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
